# REST and WS server configuration
server:
  port: ${PORT}  # Use the environment variable provided by Render
  address: 0.0.0.0

lavalink:
  server:
    password: "GidoBot"
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      mixer: true
      http: true
      local: false
    bufferDurationMs: 400  # NAS buffer duration
    frameBufferDurationMs: 5000  # Buffered audio duration in milliseconds
    youtubePlaylistLoadLimit: 6  # Number of pages at 100 each
    playerUpdateInterval: 5  # Frequency to send player updates to clients, in seconds
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true

metrics:
  prometheus:
    enabled: false
    endpoint: /metrics

sentry:
  dsn: ""
  environment: ""

logging:
  file:
    max-history: 30
    max-size: 1GB
  path: ./logs/

  level:
    root: INFO
    lavalink: INFO
